/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodosTodoIdRouteImport } from './routes/todos/$todoId'
import { Route as FetchTodosRouteImport } from './routes/fetch-todos'


const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosTodoIdRoute = TodosTodoIdRouteImport.update({
  id: '/todos/$todoId',
  path: '/todos/$todoId',
  getParentRoute: () => rootRouteImport,
} as any)
const FetchTodosRoute = FetchTodosRouteImport.update({
  id: '/fetch-todos',
  path: '/fetch-todos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todos/$todoId': typeof TodosTodoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todos/$todoId': typeof TodosTodoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/todos/$todoId': typeof TodosTodoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fetch-todos': typeof FetchTodosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todos/$todoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todos/$todoId' | '/fetch-todos'
  id: '__root__' | '/' | '/todos/$todoId' | '/fetch-todos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodosTodoIdRoute: typeof TodosTodoIdRoute
  FetchTodosRoute: typeof FetchTodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/$todoId': {
      id: '/todos/$todoId'
      path: '/todos/$todoId'
      fullPath: '/todos/$todoId'
      preLoaderRoute: typeof TodosTodoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fetch-todos': {
      id: '/fetch-todos'
      path: '/fetch-todos'
      fullPath: '/fetch-todos'
      preLoaderRoute: typeof FetchTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodosTodoIdRoute: TodosTodoIdRoute,
  FetchTodosRoute: FetchTodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
